# Generated by Django 3.2.7 on 2021-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
