# Generated by Django 3.2.7 on 2021-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210911_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
